require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PayRatesController do

  # This should return the minimal set of attributes required to create a valid
  # PayRate. As you add validations to PayRate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PayRatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all pay_rates as @pay_rates" do
      pay_rate = PayRate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pay_rates).should eq([pay_rate])
    end
  end

  describe "GET show" do
    it "assigns the requested pay_rate as @pay_rate" do
      pay_rate = PayRate.create! valid_attributes
      get :show, {:id => pay_rate.to_param}, valid_session
      assigns(:pay_rate).should eq(pay_rate)
    end
  end

  describe "GET new" do
    it "assigns a new pay_rate as @pay_rate" do
      get :new, {}, valid_session
      assigns(:pay_rate).should be_a_new(PayRate)
    end
  end

  describe "GET edit" do
    it "assigns the requested pay_rate as @pay_rate" do
      pay_rate = PayRate.create! valid_attributes
      get :edit, {:id => pay_rate.to_param}, valid_session
      assigns(:pay_rate).should eq(pay_rate)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PayRate" do
        expect {
          post :create, {:pay_rate => valid_attributes}, valid_session
        }.to change(PayRate, :count).by(1)
      end

      it "assigns a newly created pay_rate as @pay_rate" do
        post :create, {:pay_rate => valid_attributes}, valid_session
        assigns(:pay_rate).should be_a(PayRate)
        assigns(:pay_rate).should be_persisted
      end

      it "redirects to the created pay_rate" do
        post :create, {:pay_rate => valid_attributes}, valid_session
        response.should redirect_to(PayRate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pay_rate as @pay_rate" do
        # Trigger the behavior that occurs when invalid params are submitted
        PayRate.any_instance.stub(:save).and_return(false)
        post :create, {:pay_rate => {}}, valid_session
        assigns(:pay_rate).should be_a_new(PayRate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PayRate.any_instance.stub(:save).and_return(false)
        post :create, {:pay_rate => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pay_rate" do
        pay_rate = PayRate.create! valid_attributes
        # Assuming there are no other pay_rates in the database, this
        # specifies that the PayRate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PayRate.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => pay_rate.to_param, :pay_rate => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested pay_rate as @pay_rate" do
        pay_rate = PayRate.create! valid_attributes
        put :update, {:id => pay_rate.to_param, :pay_rate => valid_attributes}, valid_session
        assigns(:pay_rate).should eq(pay_rate)
      end

      it "redirects to the pay_rate" do
        pay_rate = PayRate.create! valid_attributes
        put :update, {:id => pay_rate.to_param, :pay_rate => valid_attributes}, valid_session
        response.should redirect_to(pay_rate)
      end
    end

    describe "with invalid params" do
      it "assigns the pay_rate as @pay_rate" do
        pay_rate = PayRate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PayRate.any_instance.stub(:save).and_return(false)
        put :update, {:id => pay_rate.to_param, :pay_rate => {}}, valid_session
        assigns(:pay_rate).should eq(pay_rate)
      end

      it "re-renders the 'edit' template" do
        pay_rate = PayRate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PayRate.any_instance.stub(:save).and_return(false)
        put :update, {:id => pay_rate.to_param, :pay_rate => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pay_rate" do
      pay_rate = PayRate.create! valid_attributes
      expect {
        delete :destroy, {:id => pay_rate.to_param}, valid_session
      }.to change(PayRate, :count).by(-1)
    end

    it "redirects to the pay_rates list" do
      pay_rate = PayRate.create! valid_attributes
      delete :destroy, {:id => pay_rate.to_param}, valid_session
      response.should redirect_to(pay_rates_url)
    end
  end

end
